### PR TITLE
34 Use Data to Render Race

### PR DESCRIPTION
**Pull request by CodingInGreen**

### CODE REVIEW

**Comment by CodingInGreen** [comment]
I confirmed that the behavior of the leds on the board does not match the behavior of the race. At this point @ijager has confirmed our led coordinates are properly mapped to the x,y coordinates of the race data. 

I started over trying to find the error in data formatting.

I'm pulling all the raw data from the API using this program, then sorting the data in excel and save to csv:

https://github.com/CodingInGreen/f1-led-circuit-fetch-all-raw-data

Then I'm processing to find nearest neighbor led number using this:

https://github.com/CodingInGreen/f1-led-circuit-nearest-neighbor-june

I used an excel VBA macro to replace all 0,0 x,y led numbers with 97 to eliminate the data..

And run this data through this formatting:

https://github.com/CodingInGreen/f1-led-circuit-format-data-finalized

Which gives me output.txt, which I copy the contents into f1-hardware data.rs underneath the Struct definitions.

**Comment by CodingInGreen** [comment]
I've added the f1-simulation for review. I still need to implement the playback speed. I need a bit of help with the calculation for how much data we need to fetch and the sleep wait time before fetching more data. Currently the simulation gives me an error after about an hour of playback, I believe the simulation is running out of data to visualize due to the calculation of the data fetch volume.

**Comment by CodingInGreen** [comment]
The MCU is fetching data from the API over wireless but it's too little data per API call. 

I need to increase the pipe somehow, I'm not sure how to do that just yet.

Here's a video. :)

https://www.youtube.com/watch?v=Sf_xHb8Ueuc

**Comment by ijager** [comment]
Closed in favor of #40

**Pull request closed without merging**
