### PR TITLE
Add data.rs

### PR DESCRIPTION
**Pull request by CodingInGreen**
Created these three scripts to generate the data.rs file:

https://github.com/CodingInGreen/f1-led-circuit-consolidate-timestamps

https://github.com/CodingInGreen/f1-led-circuit-check-driver-count-per-timestamp

https://github.com/CodingInGreen/f1-led-circuit-format-data-for-board

The sweet spot seemed to be 100 ms, when I did the nearest neighbor on timestamps in the 250-500 ms range, there were WAY too much data for the anchor point for comparison. When I ran consolidate-timestamps with 100 ms, then checked the driver count per timestamp, the maximum was 20 drivers!

### CODE REVIEW

**Review by ijager — CHANGES_REQUESTED** [review]
data.rs is not compiled yet since it is not included as a  module.

add 

```rust
mod data;
```

**Comment by CodingInGreen** [comment]
I just pushed again. Review when you get a moment please, I'm not sure how to handle the size on the heap. It's probably a simple fix.

**Comment by ijager** [comment]
It still has syntax errors

**Comment by ijager** [comment]
Looks good. Let's try to use it

**Review by ijager — APPROVED** [review]

**Pull request merged**
